name: pokedex_draftea
description: Pokedex - Draftea
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  dio: ^5.9.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^17.1.0
  hive_ce: ^2.19.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  pokedex_api_service:
    path: packages/pokedex_api_service
  pokedex_models:
    path: packages/pokedex_models
  pokemon_repository:
    path: packages/pokemon_repository
  pokemon_storage_service:
    path: packages/pokemon_storage_service

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/pokeball.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/pokeball.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/pokeball.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
