name: pokemon_storage_service
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  hive_ce: ^2.19.1
  pokedex_models:
    path: ../pokedex_models

dev_dependencies:
  build_runner: ^2.4.6
  hive_ce_generator: ^1.11.1
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
