name: pokedex_models
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  json_annotation: ^4.8.1
  equatable: ^2.0.8

dev_dependencies:
  build_runner: ^2.10.5
  json_serializable: ^6.11.4
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
